"""added days_to_complete to TaskTemplate

Revision ID: bd6ae9f8499c
Revises: 983275303d68
Create Date: 2022-10-08 10:51:48.279735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6ae9f8499c'
down_revision = '983275303d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_template', sa.Column('days_to_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_template', 'days_to_complete')
    # ### end Alembic commands ###
